pengaol0.96

diff --git a/recompile b/recompile
--- a/recompile
+++ b/recompile
@@ -1,119 +1,136 @@
 #!/bin/sh
 
-cd wavplay-1.4
-make clean
-make wavplay
-cp wavplay /usr/bin
-mkdir /usr/share/sound
-cp *.wav /usr/share/sound
-cd ..
+if [ -e "/usr/bin/wavplay" ];
+	then
+	echo "Wavplay exist , ok"
+	else
+	cd wavplay-1.4
+	make clean
+	if make wavplay
+		then
+		cp wavplay /usr/bin
+		mkdir /usr/share/sound
+		cp *.wav /usr/share/sound
+		else
+		echo "Compilation Error at WavPlay !"
+		exit 0
+		fi
+	cd ..
+fi
 
 export CXXFLAGS="-D_REENTRANT"
 	
+mv configure configure.tmp
+rm configure
+cp configure.ori configure
 ./configure
+rm configure
+mv configure.tmp configure
 make clean
 
 clear
 echo "PengAol V1.0 By Guth Stephane (birdy57)"
 echo "---------------------------------------"
 echo 
-echo "Cette version permet une compilation conditionnelle"
-echo "Cela impliquer que certains drivers peuvent ne pas etre inclue"
-echo "dans l'executable"
+echo "In this version you can conditinal compilation making"
+echo "(May not compile all drivers that you don't need)"
 echo 
-echo "Souhaitez-vous utilisez cette fonction ? (deconseillez au newbies lol)"
-echo "repondez par y (oui) ou n (non)"
+echo "Do you want to actived this option ?"
+echo "answer by (y or n)"
 
 read Conditionnelle
 
-if [ "$Conditionnelle" = "y" ]
+if [ "$Conditionnelle" = "y" ];
 then
-	echo "Compilation conditionelle"
+	echo "Conditional compilation"
 elif [ "$Conditionnelle" = "n" ]; then
-	echo "Compilation standart"
+	echo "Standart compilation"
 else
-	echo "Desoler votre reponsse n'est pas comprise"
+	echo "Sorry , i don't understand"
 	exit 1
 fi
 
-if [ "$Conditionnelle" = "n" ]
+if [ "$Conditionnelle" = "y" ];
 then
-echo "#define WITH_PPP" >> config.h
-echo "#define WITH_MODEM" >> config.h
-echo "#define WITH_TUNTAP" >> config.h
-echo "#define WITH_CABLE" >> config.h
-fi
-
-if [ "$Conditionnelle" = "y" ]
-then
-	echo "Compiler le driver Modem ? (y/n)"
+	echo "Do you want to use the modem driver ? (y/n)"
 	read Rep
-	if [ "$Rep" = "y" ]
+	if [ "$Rep" = "y" ];
 	then
 		echo "#define WITH_MODEM" >> config.h
 	fi
 
-	echo "Compiler le driver Cable? (y/n)"
+	echo "Do you want to use the Cable driver ? (y/n)"
 	read Rep
-	if [ "$Rep" = "y" ]
+	if [ "$Rep" = "y" ];
 	then
 		echo "#define WITH_CABLE" >> config.h
 	fi
 
-	echo "Compiler le driver Ppp ? (y/n)"
+	echo "Do you want to use the Ppp driver ? (y/n)"
 	read Rep
-	if [ "$Rep" = "y" ]
+	if [ "$Rep" = "y" ];
 	then
 		echo "#define WITH_PPP" >> config.h
 	fi
 
-	echo "Compiler le driver TunTap ? (y/n)"
+	echo "Do you want to use the TunTap driver ? (y/n)"
 	read Rep
-	if [ "$Rep" = "y" ]
+	if [ "$Rep" = "y" ];
 	then
 		echo "#define WITH_TUNTAP" >> config.h
 	fi
 
-	echo "Compiler le l'option Debug ? (y/n)"
-	echo "Attention ! cela peut ralentir la connection"
+	echo "Do you want to use the Debug ? (y/n)"
+	echo "Warning ! that can slow down the connection"
 	read Rep
-	if [ "$Rep" = "y" ]
+	if [ "$Rep" = "y" ];
 	then
 		echo "#define WITH_DEBUG" >> config.h
 	fi
-
+else
+	echo "#define WITH_PPP" >> config.h
+	echo "#define WITH_MODEM" >> config.h
+	echo "#define WITH_TUNTAP" >> config.h
+	echo "#define WITH_CABLE" >> config.h
 fi
 	
-make
+if make
+	then
+	echo "Compilation Ok"
+	else
+	echo "Error by compilation !!!"
+	exit 1
+	fi
+
 
 if cat /proc/version | grep -q 2.2.
 then
- if [ -e "/dev/tap0" ]
+ if [ -e "/dev/tap0" ];
  then
- echo "Le fichier /dev/tap0 existe : OK"
+ echo "/dev/tap0 exist : OK"
  else
- echo "Creation de /dev/tap0"
+ echo "Creating /dev/tap0"
  mknod /dev/tap0 c 36 16
  fi
 fi
 
 # on change les droit de pengaol et on copie
 
-if [ -e "/etc/Pengaol" ]
+if [ -e "/etc/Pengaol" ];
  	then
-	echo "/etc/Pengaol existe deja"
+	echo "/etc/Pengaol exist , all right"
 else
 	mkdir /etc/Pengaol
 fi
 
 
 
-cd pengaol2
-chmod 755 pengaol2
-chmod +s pengaol2
+cd peng
+chmod 755 peng
+chmod +s peng
 
 echo "copy pengaol --> /usr/bin"
-cp pengaol2 /usr/bin/pengaol
+cp peng /usr/bin/pengaol
 echo "copy PengMessages.txt --> /etc/Pengaol"
 cp PengMessages.txt /etc/Pengaol
 echo "copy Dns --> /etc/Pengaol"
@@ -126,27 +143,72 @@ chmod 600 /dev/ttyS0
 chmod 600 /dev/ttyS1
 cd ..
 
+#langue allemande
+
+if echo $LANG | grep -q de 
+	then
+	echo "recompile has gefunden das sir ein deutch linux utilisieren"
+	echo "Wenn sie zum ein deutch aol server verbindet mochten"
+	echo "sir mussen am erte das /etc/Pengaol/PengAol.conf editieren"
+	echo "und im [CModemDriver] , ServerType=French bei ServerType=German anderen"
+	echo " "
+	echo "recompile at found german linux"
+	echo "If you want to a german aol server connecting"
+	echo "You must /etc/Pengaol/PengAol.conf edit"
+	echo "and in [CModemDriver] , ServerType=French with ServerType=German change"
+	fi
+
+#login password
+
+if pengaol -ListUser | grep -q "No User" 
+	then
+	echo "You must at first add one user"
+	echo "Please enter your login"
+	read Login
+	echo "Please enter you password"
+	read PassWord
+	pengaol -AddUser "$Login" "$PassWord"
+	echo "You can add another User with pengaol -AddUSer [login] [password]"
+	fi
 echo "Voulez-vous visualiser la documentation ? (y/n)"
 read Rep
-if [ "$Rep" = "y" ]
+if [ "$Rep" = "y" ];
 then
 	echo "Quel nagivateur souhaitez-vous utilisez (1-netscape, 2-konqueror, 3-opera) ??"
 	read Rep
-	cd Doc\&Aide
+	cd Doc
 	cd fr
-	if [ "$Rep" = "1" ]
+	if [ "$Rep" = "1" ];
 	then
 	netscape index.html &
 	fi	
-	if [ "$Rep" = "2" ]
+	if [ "$Rep" = "2" ];
 	then
 	konqueror index.html &
 	fi	
-	if [ "$Rep" = "3" ]
+	if [ "$Rep" = "3" ];
 	then
 	opera index.html &
 	fi	
 fi
+
+echo "Installtion successfull"
+echo "You can verify that pengaol is correctly configured"
+echo "by editing /etc/Pengaol/PengAol.conf"
+echo " "
+echo "To connect you tape : pengaol -Connect [Login]"
+echo " "
+echo "Have a lot of fun !! "
+echo "Birdy57"
+
+
+
+
+
+
+
+
+
 
 
 
